# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yjung93/work/study/framework

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yjung93/work/study/framework

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yjung93/work/study/framework/CMakeFiles /home/yjung93/work/study/framework//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yjung93/work/study/framework/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named example_reactor_client

# Build rule for target.
example_reactor_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example_reactor_client
.PHONY : example_reactor_client

# fast build rule for target.
example_reactor_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_reactor_client.dir/build.make CMakeFiles/example_reactor_client.dir/build
.PHONY : example_reactor_client/fast

#=============================================================================
# Target rules for targets named example_reactor_server

# Build rule for target.
example_reactor_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example_reactor_server
.PHONY : example_reactor_server

# fast build rule for target.
example_reactor_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_reactor_server.dir/build.make CMakeFiles/example_reactor_server.dir/build
.PHONY : example_reactor_server/fast

applications/example_reactor/Acceptor.o: applications/example_reactor/Acceptor.cpp.o
.PHONY : applications/example_reactor/Acceptor.o

# target to build an object file
applications/example_reactor/Acceptor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_reactor_server.dir/build.make CMakeFiles/example_reactor_server.dir/applications/example_reactor/Acceptor.cpp.o
.PHONY : applications/example_reactor/Acceptor.cpp.o

applications/example_reactor/Acceptor.i: applications/example_reactor/Acceptor.cpp.i
.PHONY : applications/example_reactor/Acceptor.i

# target to preprocess a source file
applications/example_reactor/Acceptor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_reactor_server.dir/build.make CMakeFiles/example_reactor_server.dir/applications/example_reactor/Acceptor.cpp.i
.PHONY : applications/example_reactor/Acceptor.cpp.i

applications/example_reactor/Acceptor.s: applications/example_reactor/Acceptor.cpp.s
.PHONY : applications/example_reactor/Acceptor.s

# target to generate assembly for a file
applications/example_reactor/Acceptor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_reactor_server.dir/build.make CMakeFiles/example_reactor_server.dir/applications/example_reactor/Acceptor.cpp.s
.PHONY : applications/example_reactor/Acceptor.cpp.s

applications/example_reactor/MainClient.o: applications/example_reactor/MainClient.cpp.o
.PHONY : applications/example_reactor/MainClient.o

# target to build an object file
applications/example_reactor/MainClient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_reactor_client.dir/build.make CMakeFiles/example_reactor_client.dir/applications/example_reactor/MainClient.cpp.o
.PHONY : applications/example_reactor/MainClient.cpp.o

applications/example_reactor/MainClient.i: applications/example_reactor/MainClient.cpp.i
.PHONY : applications/example_reactor/MainClient.i

# target to preprocess a source file
applications/example_reactor/MainClient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_reactor_client.dir/build.make CMakeFiles/example_reactor_client.dir/applications/example_reactor/MainClient.cpp.i
.PHONY : applications/example_reactor/MainClient.cpp.i

applications/example_reactor/MainClient.s: applications/example_reactor/MainClient.cpp.s
.PHONY : applications/example_reactor/MainClient.s

# target to generate assembly for a file
applications/example_reactor/MainClient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_reactor_client.dir/build.make CMakeFiles/example_reactor_client.dir/applications/example_reactor/MainClient.cpp.s
.PHONY : applications/example_reactor/MainClient.cpp.s

applications/example_reactor/MainServer.o: applications/example_reactor/MainServer.cpp.o
.PHONY : applications/example_reactor/MainServer.o

# target to build an object file
applications/example_reactor/MainServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_reactor_server.dir/build.make CMakeFiles/example_reactor_server.dir/applications/example_reactor/MainServer.cpp.o
.PHONY : applications/example_reactor/MainServer.cpp.o

applications/example_reactor/MainServer.i: applications/example_reactor/MainServer.cpp.i
.PHONY : applications/example_reactor/MainServer.i

# target to preprocess a source file
applications/example_reactor/MainServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_reactor_server.dir/build.make CMakeFiles/example_reactor_server.dir/applications/example_reactor/MainServer.cpp.i
.PHONY : applications/example_reactor/MainServer.cpp.i

applications/example_reactor/MainServer.s: applications/example_reactor/MainServer.cpp.s
.PHONY : applications/example_reactor/MainServer.s

# target to generate assembly for a file
applications/example_reactor/MainServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_reactor_server.dir/build.make CMakeFiles/example_reactor_server.dir/applications/example_reactor/MainServer.cpp.s
.PHONY : applications/example_reactor/MainServer.cpp.s

applications/example_reactor/ServerEventHandler.o: applications/example_reactor/ServerEventHandler.cpp.o
.PHONY : applications/example_reactor/ServerEventHandler.o

# target to build an object file
applications/example_reactor/ServerEventHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_reactor_server.dir/build.make CMakeFiles/example_reactor_server.dir/applications/example_reactor/ServerEventHandler.cpp.o
.PHONY : applications/example_reactor/ServerEventHandler.cpp.o

applications/example_reactor/ServerEventHandler.i: applications/example_reactor/ServerEventHandler.cpp.i
.PHONY : applications/example_reactor/ServerEventHandler.i

# target to preprocess a source file
applications/example_reactor/ServerEventHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_reactor_server.dir/build.make CMakeFiles/example_reactor_server.dir/applications/example_reactor/ServerEventHandler.cpp.i
.PHONY : applications/example_reactor/ServerEventHandler.cpp.i

applications/example_reactor/ServerEventHandler.s: applications/example_reactor/ServerEventHandler.cpp.s
.PHONY : applications/example_reactor/ServerEventHandler.s

# target to generate assembly for a file
applications/example_reactor/ServerEventHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_reactor_server.dir/build.make CMakeFiles/example_reactor_server.dir/applications/example_reactor/ServerEventHandler.cpp.s
.PHONY : applications/example_reactor/ServerEventHandler.cpp.s

framework/v_1_0/EventHandler.o: framework/v_1_0/EventHandler.cpp.o
.PHONY : framework/v_1_0/EventHandler.o

# target to build an object file
framework/v_1_0/EventHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_reactor_server.dir/build.make CMakeFiles/example_reactor_server.dir/framework/v_1_0/EventHandler.cpp.o
.PHONY : framework/v_1_0/EventHandler.cpp.o

framework/v_1_0/EventHandler.i: framework/v_1_0/EventHandler.cpp.i
.PHONY : framework/v_1_0/EventHandler.i

# target to preprocess a source file
framework/v_1_0/EventHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_reactor_server.dir/build.make CMakeFiles/example_reactor_server.dir/framework/v_1_0/EventHandler.cpp.i
.PHONY : framework/v_1_0/EventHandler.cpp.i

framework/v_1_0/EventHandler.s: framework/v_1_0/EventHandler.cpp.s
.PHONY : framework/v_1_0/EventHandler.s

# target to generate assembly for a file
framework/v_1_0/EventHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_reactor_server.dir/build.make CMakeFiles/example_reactor_server.dir/framework/v_1_0/EventHandler.cpp.s
.PHONY : framework/v_1_0/EventHandler.cpp.s

framework/v_1_0/Reactor.o: framework/v_1_0/Reactor.cpp.o
.PHONY : framework/v_1_0/Reactor.o

# target to build an object file
framework/v_1_0/Reactor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_reactor_server.dir/build.make CMakeFiles/example_reactor_server.dir/framework/v_1_0/Reactor.cpp.o
.PHONY : framework/v_1_0/Reactor.cpp.o

framework/v_1_0/Reactor.i: framework/v_1_0/Reactor.cpp.i
.PHONY : framework/v_1_0/Reactor.i

# target to preprocess a source file
framework/v_1_0/Reactor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_reactor_server.dir/build.make CMakeFiles/example_reactor_server.dir/framework/v_1_0/Reactor.cpp.i
.PHONY : framework/v_1_0/Reactor.cpp.i

framework/v_1_0/Reactor.s: framework/v_1_0/Reactor.cpp.s
.PHONY : framework/v_1_0/Reactor.s

# target to generate assembly for a file
framework/v_1_0/Reactor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_reactor_server.dir/build.make CMakeFiles/example_reactor_server.dir/framework/v_1_0/Reactor.cpp.s
.PHONY : framework/v_1_0/Reactor.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... example_reactor_client"
	@echo "... example_reactor_server"
	@echo "... applications/example_reactor/Acceptor.o"
	@echo "... applications/example_reactor/Acceptor.i"
	@echo "... applications/example_reactor/Acceptor.s"
	@echo "... applications/example_reactor/MainClient.o"
	@echo "... applications/example_reactor/MainClient.i"
	@echo "... applications/example_reactor/MainClient.s"
	@echo "... applications/example_reactor/MainServer.o"
	@echo "... applications/example_reactor/MainServer.i"
	@echo "... applications/example_reactor/MainServer.s"
	@echo "... applications/example_reactor/ServerEventHandler.o"
	@echo "... applications/example_reactor/ServerEventHandler.i"
	@echo "... applications/example_reactor/ServerEventHandler.s"
	@echo "... framework/v_1_0/EventHandler.o"
	@echo "... framework/v_1_0/EventHandler.i"
	@echo "... framework/v_1_0/EventHandler.s"
	@echo "... framework/v_1_0/Reactor.o"
	@echo "... framework/v_1_0/Reactor.i"
	@echo "... framework/v_1_0/Reactor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

